### ISSUE TITLE
ViewModel from View instead of Activity or Fragment

### ISSUE THREAD

**Issue by GSala** [bufferapp/android-clean-architecture-mvi-boilerplate#4]
When trying to encapsulate some behavior in a View instead of an Activity or a Fragment, I do not have access to the ViewModelProvider. What would be the mot appropriate way of having the same architecture when using Views?

I can see at least 4 options. 

1.  Pass the ViewModelProvider as an argument to the View constructor
2.  Pass the already obtained ViewModel as an argument to the View constructor
3.  Pass a LifecycleOwner as an argument to the View constructor
4.  Hold the ViewModel in the containing Fragment/Activity and expose events from the view and consume states.

**Comment by ghost** [comment]
Only third option. Check GithubSample in android-architecture-component repo for an example. Please also check: https://academy.realm.io/posts/mvc-vs-mvp-vs-mvvm-vs-mvi-mobilization-moskala/ to get to know better a role of ViewModel in Android app's architecture.
